### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by mcbortolozzo** [Xiao-Ming/ChordRecognitionMIDITrainedExtractor#2]
Hello,
I've been trying to use the code you provided on this repository with a dataset of around 500 songs. When retraining the network I receive an out of memory exception from CuPy. From some calculations I made based on the amount of songs and the associated memory usage, it seems I'd require around 500Gb of GPU memory to train the network with my dataset. Are you aware of this issue? Is there any workaround for it, or a way to reduce memory usage when training?

**Comment by Xiao-Ming** [comment]
Hi,
the GPU memory usage is not intended to be related to the amount of songs. The data would occupy much CPU-side memory, though. 
GPU memory is mainly used to store the computational graph during the forward computation, which is released every time the computation is done. To reduce GPU memory usage, you can try decreasing the batch size of each training iteration. This can be done by modifying the values of DECODER_TRAIN_BATCH and DNN_TRAIN_BATCH in const.py.

**Comment by mcbortolozzo** [comment]
Hi, thanks for the quick reply!
I tried changing the batch sizes, but it didn't have any effect on my current issue. When taking a look at the code, it seems to me that the out of memory error occurs before the batch sizes are taken into account, during the preparation of the dataset. This is actually being done on the GPU memory, from what I checked here on my system. Here's the error message I'm getting from it:
```
Traceback (most recent call last):
  File "Train_Decoder.py", line 44, in <module>
    training.TrainNStepRNN(None, epoch=args.e[0], featmodel=args.f, augment=args.a)
  File "/home/mcbortolozzo/Downloads/ChordRecognitionMIDITrainedExtractor-master/training.py", line 246, in TrainNStepRNN
    feature = cp.asnumpy(dnn.GetFeature(cp.asarray(cqt)).data)
  File "/home/mcbortolozzo/Downloads/ChordRecognitionMIDITrainedExtractor-master/networks.py", line 55, in GetFeature
    o = F.sigmoid(self(x[None,:,:,:]))
  File "/home/mcbortolozzo/Downloads/ChordRecognitionMIDITrainedExtractor-master/networks.py", line 48, in __call__
    h1 = self.res1(h1)
  File "/home/mcbortolozzo/Downloads/ChordRecognitionMIDITrainedExtractor-master/networks.py", line 30, in __call__
    h = F.leaky_relu(self.norm2(self.conv2(h)))
  File "/home/mcbortolozzo/.local/lib/python3.6/site-packages/chainer/link.py", line 287, in __call__
    out = forward(*args, **kwargs)
  File "/home/mcbortolozzo/.local/lib/python3.6/site-packages/chainer/links/normalization/batch_renormalization.py", line 88, in forward
    x, gamma, beta, mean, var, self.eps)
  File "/home/mcbortolozzo/.local/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 992, in fixed_batch_normalization
    var))[0]
  File "/home/mcbortolozzo/.local/lib/python3.6/site-packages/chainer/function_node.py", line 334, in apply
    outputs = self.forward(in_data)
  File "/home/mcbortolozzo/.local/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 671, in forward
    mode.is_for_conv2d, mode.get_cudnn_mode())
  File "cupy/cudnn.pyx", line 2200, in cupy.cudnn.batch_normalization_forward_inference
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 545, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1239, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1260, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1038, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1058, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 780, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 784,293,888 bytes (allocated so far: 5,492,345,344 bytes).
```
If I could switch that memory load to the CPU-side memory, that would be great. Any idea on what might be causing such an issue?

**Comment by Xiao-Ming** [comment]
You'll have to do some careful modification on the script to switch to CPU mode, because the training script is such a mess. I really should re-write the whole scripts using Chainer's Trainer API...

However I figured out the problem: there was a mistake in the script for calculating H-CQT spectrogram, making the spectrogram unexpectedly large (8x the intended size). I have fixed it in my repository.

Furthermore, I fixed some other fatal mistakes in the training script, which I guess you've already realized them since you've managed to the training loop. Now I believe the script will use much less GPU memory after you re-compute HCQT. It used at most 4Gb GPU memory in my experiment.
(Actually the GPU memory usage depends on the length of each song file, so the GPU memory may still exceed if you have a very long audio file, maybe longer than 7 minutes) 

Please tell me if there is any other problem. Apologies for the inconvenience! I promise I'll prepare better scripts soon.

**Comment by mcbortolozzo** [comment]
Thanks for the updates! After recalculating the HCQT with the new version you uploaded the memory usage seems to be stable and much lower. I was now able to train it until the end, and will try out the network further. If I detect anything else unusual, I'll be sure to let you know.
Thanks again for the help and quick replies!
